[tools]
bun = "1.2.19"

[hooks]
postinstall = "bun i --frozen-lockfile"

[tasks.format]
run = ["bun run format", "bun run typecheck"]
alias = "lint"

[tasks.dev]
run = "bun run dev"

[tasks.build]
run = "bun run build"

[tasks.zip]
run = ["bun run zip", "bun run zip:firefox"]
