name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - run: mise run zip
      - uses: actions/upload-artifact@v4
        with:
          name: extension
          path: output/*.zip
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/*.zip
